In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)

Pandas: 2.3.3
NumPy: 2.5.1
Scikit-learn: 1.9.0

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

# Display all columns when needed
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

In [4]:
RAW_DIR = Path("../data/raw")

print("Files in raw data folder:")
for file in RAW_DIR.iterdir():
    print(file.name)

Files in raw data folder:
.gitkeep
GSE176307_BACI_Omniseq_Sample_Name_Key_submitted_GEO_v2.csv.gz
GSE176307_salmon_tpm_gene.matrix.tsv.gz

In [5]:
expression = pd.read_csv(
    RAW_DIR / "GSE176307_salmon_tpm_gene.matrix.tsv.gz",
    sep="\t",
    compression="gzip"
)

print("Expression matrix loaded successfully!\n")
print("Shape:", expression.shape)
expression.head()

Expression matrix loaded successfully!

Shape: (58387, 93)

,Unnamed: 0,RS-03238953,RS-03238954,RS-03238955,RS-03238956,RS-03238957,RS-03238958,RS-03238959,RS-03238960,RS-03238961,RS-03238962,RS-03238963,RS-03238964,RS-03238965,RS-03238966,RS-03238967,RS-03238968,RS-03238969,RS-03238970,RS-03238971,RS-03238972,RS-03238973,RS-03238974,RS-03238975,RS-03238976,RS-03238977,RS-03238978,RS-03238979,RS-03238980,RS-03238981,RS-03238982,RS-03238983,RS-03238984,RS-03238985,RS-03238986,RS-03238987,RS-03238988,RS-03238989,RS-03238990,RS-03238991,RS-03238992,RS-03238993,RS-03238994,RS-03238995,RS-03238996,RS-03238997,RS-03238998,RS-03238999,RS-03239000,RS-03239001,RS-03239002,RS-03239003,RS-03239004,RS-03239005,RS-03239006,RS-03239007,RS-03239008,RS-03239009,RS-03239010,RS-03239011,RS-03239012,RS-03239013,RS-03239014,RS-03239015,RS-03239016,RS-03239017,RS-03239018,RS-03239019,RS-03239020,RS-03239021,RS-03239022,RS-03239023,RS-03239024,RS-03239025,RS-03239026,RS-03239027,RS-03239028,RS-03239029,RS-03239030,RS-03239031,RS-03239032,RS-03239033,RS-03239034,RS-03239035,RS-03239036,RS-03239037,RS-03239038,RS-03239039,RS-03239040,RS-03239041,RS-03239042,RS-03239043,RS-03239044
0,5S_rRNA,40.473330,4.791860,7.564440,23.424800,23.235700,13.571400,5.263550,5.914640,3.068190,20.847100,0.00000,2.84214,21.208800,5.340600,3.17614,33.867400,6.950450,3.122450,29.31384,0.000000,5.088390,18.854480,22.40620,9.716520,6.573750,12.072100,24.87490,5.790710,16.778700,10.817920,11.66917,7.080540,5.89611,14.36250,18.521900,0.000000,12.359200,11.03400,19.879100,16.849900,21.870800,6.629690,22.550400,32.663500,12.801300,20.77140,33.724500,15.19070,23.941800,37.114900,7.539430,9.375720,13.076600,3.719060,16.426900,9.530910,9.621850,15.05900,29.383200,7.831850,13.010100,8.278770,13.020920,6.170270,5.251160,7.66098,0.000000,2.59234,11.433700,22.270600,7.931610,8.39476,26.36320,14.538100,6.343680,7.09500,30.82027,6.67953,65.575500,72.34580,28.632200,3.750990,9.514610,38.68750,19.193200,29.155500,12.656600,0.000000,9.71791,3.545100,0.000000,0.00000
1,5_8S_rRNA,0.735559,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.31735,2.725320,0.000000,0.000000,1.01504,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.438120,0.000000,0.000000,0.000000,0.000000,0.000000,2.893380,0.00000,0.000000,2.78306,1.252860,0.000000,0.000000,0.00000,0.00000,0.000000,1.720810,0.00000,0.00000,0.00000,0.000000,0.00000,2.010520,0.000000,0.000000,0.00000,1.487430,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000
2,7SK,0.382188,0.280699,0.241591,2.978596,0.858723,0.000000,0.308608,0.860673,2.492087,1.176219,0.00000,0.00000,2.206782,0.303812,0.73484,0.321808,0.591332,1.969570,0.00000,0.777015,0.642402,0.585223,0.00000,0.288206,0.635172,0.839613,0.00000,1.303106,0.296868,0.890924,0.00000,0.475508,1.38550,0.00000,0.633014,0.997877,0.609655,0.00000,1.807414,2.694988,1.276951,6.239258,0.741838,0.000000,1.458924,1.13095,2.484678,0.00000,1.201880,0.369496,1.327632,1.810222,0.232756,3.713930,1.877049,0.423165,0.312834,0.00000,0.000000,0.000000,0.323841,0.339836,1.278997,0.000000,0.335932,0.00000,0.410154,0.62298,0.307167,0.728874,0.913294,0.00000,0.00000,0.875458,0.386956,0.00000,0.00000,0.00000,0.294297,0.32831,0.479175,1.975373,1.124356,1.38709,0.313099,0.476742,1.314230,0.000000,0.00000,1.296487,0.395179,0.00000
3,A1BG,7.538390,2.731250,4.731560,11.375700,9.665630,8.470140,15.190700,2.134140,1.665490,5.196470,8.92214,4.98055,11.346400,7.001000,2.62676,20.165800,4.159740,1.872830,12.90280,8.964900,15.359000,91.847100,8.48751,4.904450,4.557930,2.828820,9.31402,5.084460,4.091910,4.864660,7.10343,40.203200,9.28335,12.30500,14.246400,7.309020,2.010710,1.98562,2.535050,7.205750,18.865500,3.730100,1.748060,2.913690,3.524980,23.85200,1.868650,13.48300,5.349900,13.780300,3.602990,3.486760,33.692500,0.395513,8.237160,30.525400,10.718300,13.91340,4.396780,5.973760,3.350700,0.895223,9.665870,2.925060,19.899900,14.43840,10.576800,5.08876,11.460700,10.091900,9.326250,14.84080,5.95915,6.222740,2.415110,6.59075,11.82680,14.07070,10.159200,2.53030,2.912380,3.697280,0.359733,2.77869,13.866700,12.569800,3.488230,2.253910,1.08286,1.582650,4.251720,22.75370
4,A1BG-AS1,1.827090,1.059760,2.117120,1.245820,3.242580,0.669402,5.597850,1.339760,0.552307,0.649324,1.57104,1.20736,2.776230,1.210420,1.17964,4.118550,3.602640,0.221111,3.18057,3.334600,3.148970,4.134170,2.96816,2.184440,3.815960,3.178710,3.14951,1.629090,2.817680,2.408640,3.24197,5.939370,3.79430,5.12258,3.665250,3.185530,1.629620,0.64700,0.939661,0.930587,2.181560,1.331100,0.662754,0.868483,1.014070,6.13937,4.637700,1.79243,0.923945,2.077570,1.899980,2.453350,4.034170,0.711186,2.361100,7.065610,2.109460,2.51323,0.715256,0.750577,1.982590,1.507060,1.126790,0.814948,5.991130,1.80101,1.288600,2.44683,3.747710,5.110980,1.380890,2.63784,2.12112,2.573690,0.674932,1.54712,1.13957,2.21067,1.209590,1.22214,1.622530,1.008290,1.673490,1.83108,1.979040,1.958780,0.442682,0.785791,0.69881,0.900695,0.608497,4.34096

In [6]:
clinical = pd.read_csv(
    RAW_DIR / "GSE176307_BACI_Omniseq_Sample_Name_Key_submitted_GEO_v2.csv.gz",
    compression="gzip"
)

print("Clinical metadata loaded successfully!\n")
print("Shape:", clinical.shape)
clinical.head()

Clinical metadata loaded successfully!

Shape: (89, 2)

  Sample ID Omniseq_RS_ID (RNAseq)
0   BACI170            RS-03238953
1   BACI191            RS-03238954
2   BACI192            RS-03238955
3   BACI190            RS-03238956
4   BACI160            RS-03238957

In [7]:
print("Expression Info")
print("=" * 60)
expression.info()

print("\nClinical Info")
print("=" * 60)
clinical.info()

Expression Info
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58387 entries, 0 to 58386
Data columns (total 93 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   58387 non-null  object
 1   RS-03238953  58387 non-null  float64
 2   RS-03238954  58387 non-null  float64
 3   RS-03238955  58387 non-null  float64
 4   RS-03238956  58387 non-null  float64
 5   RS-03238957  58387 non-null  float64
 6   RS-03238958  58387 non-null  float64
 7   RS-03238959  58387 non-null  float64
 8   RS-03238960  58387 non-null  float64
 9   RS-03238961  58387 non-null  float64
 10  RS-03238962  58387 non-null  float64
 11  RS-03238963  58387 non-null  float64
 12  RS-03238964  58387 non-null  float64
 13  RS-03238965  58387 non-null  float64
 14  RS-03238966  58387 non-null  float64
 15  RS-03238967  58387 non-null  float64
 16  RS-03238968  58387 non-null  float64
 17  RS-03238969  58387 non-null  float64
 18  RS-03238970  58387 non-null  float64
 19  RS-03238971  58387 non-null  float64
 20  RS-03238972  58387 non-null  float64
 21  RS-03238973  58387 non-null  float64
 22  RS-03238974  58387 non-null  float64
 23  RS-03238975  58387 non-null  float64
 24  RS-03238976  58387 non-null  float64
 25  RS-03238977  58387 non-null  float64
 26  RS-03238978  58387 non-null  float64
 27  RS-03238979  58387 non-null  float64
 28  RS-03238980  58387 non-null  float64
 29  RS-03238981  58387 non-null  float64
 30  RS-03238982  58387 non-null  float64
 31  RS-03238983  58387 non-null  float64
 32  RS-03238984  58387 non-null  float64
 33  RS-03238985  58387 non-null  float64
 34  RS-03238986  58387 non-null  float64
 35  RS-03238987  58387 non-null  float64
 36  RS-03238988  58387 non-null  float64
 37  RS-03238989  58387 non-null  float64
 38  RS-03238990  58387 non-null  float64
 39  RS-03238991  58387 non-null  float64
 40  RS-03238992  58387 non-null  float64
 41  RS-03238993  58387 non-null  float64
 42  RS-03238994  58387 non-null  float64
 43  RS-03238995  58387 non-null  float64
 44  RS-03238996  58387 non-null  float64
 45  RS-03238997  58387 non-null  float64
 46  RS-03238998  58387 non-null  float64
 47  RS-03238999  58387 non-null  float64
 48  RS-03239000  58387 non-null  float64
 49  RS-03239001  58387 non-null  float64
 50  RS-03239002  58387 non-null  float64
 51  RS-03239003  58387 non-null  float64
 52  RS-03239004  58387 non-null  float64
 53  RS-03239005  58387 non-null  float64
 54  RS-03239006  58387 non-null  float64
 55  RS-03239007  58387 non-null  float64
 56  RS-03239008  58387 non-null  float64
 57  RS-03239009  58387 non-null  float64
 58  RS-03239010  58387 non-null  float64
 59  RS-03239011  58387 non-null  float64
 60  RS-03239012  58387 non-null  float64
 61  RS-03239013  58387 non-null  float64
 62  RS-03239014  58387 non-null  float64
 63  RS-03239015  58387 non-null  float64
 64  RS-03239016  58387 non-null  float64
 65  RS-03239017  58387 non-null  float64
 66  RS-03239018  58387 non-null  float64
 67  RS-03239019  58387 non-null  float64
 68  RS-03239020  58387 non-null  float64
 69  RS-03239021  58387 non-null  float64
 70  RS-03239022  58387 non-null  float64
 71  RS-03239023  58387 non-null  float64
 72  RS-03239024  58387 non-null  float64
 73  RS-03239025  58387 non-null  float64
 74  RS-03239026  58387 non-null  float64
 75  RS-03239027  58387 non-null  float64
 76  RS-03239028  58387 non-null  float64
 77  RS-03239029  58387 non-null  float64
 78  RS-03239030  58387 non-null  float64
 79  RS-03239031  58387 non-null  float64
 80  RS-03239032  58387 non-null  float64
 81  RS-03239033  58387 non-null  float64
 82  RS-03239034  58387 non-null  float64
 83  RS-03239035  58387 non-null  float64
 84  RS-03239036  58387 non-null  float64
 85  RS-03239037  58387 non-null  float64
 86  RS-03239038  58387 non-null  float64
 87  RS-03239039  58387 non-null  float64
 88  RS-03239040  58387 non-null  float64
 89  RS-03239041  58387 non-null  float64
 90  RS-03239042  58387 non-null  float64
 91  RS-03239043  58387 non-null  float64
 92  RS-03239044  58387 non-null  float64
dtypes: float64(92), object(1)
memory usage: 41.4+ MB

Clinical Info
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sample ID               89 non-null     object
 1   Omniseq_RS_ID (RNAseq)  89 non-null     object
dtypes: object(2)
memory usage: 1.5+ KB

In [8]:
print(expression.shape)

(58387, 93)

In [9]:
print(clinical.shape)

(89, 2)

In [10]:
expression.head()

,Unnamed: 0,RS-03238953,RS-03238954,RS-03238955,RS-03238956,RS-03238957,RS-03238958,RS-03238959,RS-03238960,RS-03238961,RS-03238962,RS-03238963,RS-03238964,RS-03238965,RS-03238966,RS-03238967,RS-03238968,RS-03238969,RS-03238970,RS-03238971,RS-03238972,RS-03238973,RS-03238974,RS-03238975,RS-03238976,RS-03238977,RS-03238978,RS-03238979,RS-03238980,RS-03238981,RS-03238982,RS-03238983,RS-03238984,RS-03238985,RS-03238986,RS-03238987,RS-03238988,RS-03238989,RS-03238990,RS-03238991,RS-03238992,RS-03238993,RS-03238994,RS-03238995,RS-03238996,RS-03238997,RS-03238998,RS-03238999,RS-03239000,RS-03239001,RS-03239002,RS-03239003,RS-03239004,RS-03239005,RS-03239006,RS-03239007,RS-03239008,RS-03239009,RS-03239010,RS-03239011,RS-03239012,RS-03239013,RS-03239014,RS-03239015,RS-03239016,RS-03239017,RS-03239018,RS-03239019,RS-03239020,RS-03239021,RS-03239022,RS-03239023,RS-03239024,RS-03239025,RS-03239026,RS-03239027,RS-03239028,RS-03239029,RS-03239030,RS-03239031,RS-03239032,RS-03239033,RS-03239034,RS-03239035,RS-03239036,RS-03239037,RS-03239038,RS-03239039,RS-03239040,RS-03239041,RS-03239042,RS-03239043,RS-03239044
0,5S_rRNA,40.473330,4.791860,7.564440,23.424800,23.235700,13.571400,5.263550,5.914640,3.068190,20.847100,0.00000,2.84214,21.208800,5.340600,3.17614,33.867400,6.950450,3.122450,29.31384,0.000000,5.088390,18.854480,22.40620,9.716520,6.573750,12.072100,24.87490,5.790710,16.778700,10.817920,11.66917,7.080540,5.89611,14.36250,18.521900,0.000000,12.359200,11.03400,19.879100,16.849900,21.870800,6.629690,22.550400,32.663500,12.801300,20.77140,33.724500,15.19070,23.941800,37.114900,7.539430,9.375720,13.076600,3.719060,16.426900,9.530910,9.621850,15.05900,29.383200,7.831850,13.010100,8.278770,13.020920,6.170270,5.251160,7.66098,0.000000,2.59234,11.433700,22.270600,7.931610,8.39476,26.36320,14.538100,6.343680,7.09500,30.82027,6.67953,65.575500,72.34580,28.632200,3.750990,9.514610,38.68750,19.193200,29.155500,12.656600,0.000000,9.71791,3.545100,0.000000,0.00000
1,5_8S_rRNA,0.735559,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.31735,2.725320,0.000000,0.000000,1.01504,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.438120,0.000000,0.000000,0.000000,0.000000,0.000000,2.893380,0.00000,0.000000,2.78306,1.252860,0.000000,0.000000,0.00000,0.00000,0.000000,1.720810,0.00000,0.00000,0.00000,0.000000,0.00000,2.010520,0.000000,0.000000,0.00000,1.487430,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000
2,7SK,0.382188,0.280699,0.241591,2.978596,0.858723,0.000000,0.308608,0.860673,2.492087,1.176219,0.00000,0.00000,2.206782,0.303812,0.73484,0.321808,0.591332,1.969570,0.00000,0.777015,0.642402,0.585223,0.00000,0.288206,0.635172,0.839613,0.00000,1.303106,0.296868,0.890924,0.00000,0.475508,1.38550,0.00000,0.633014,0.997877,0.609655,0.00000,1.807414,2.694988,1.276951,6.239258,0.741838,0.000000,1.458924,1.13095,2.484678,0.00000,1.201880,0.369496,1.327632,1.810222,0.232756,3.713930,1.877049,0.423165,0.312834,0.00000,0.000000,0.000000,0.323841,0.339836,1.278997,0.000000,0.335932,0.00000,0.410154,0.62298,0.307167,0.728874,0.913294,0.00000,0.00000,0.875458,0.386956,0.00000,0.00000,0.00000,0.294297,0.32831,0.479175,1.975373,1.124356,1.38709,0.313099,0.476742,1.314230,0.000000,0.00000,1.296487,0.395179,0.00000
3,A1BG,7.538390,2.731250,4.731560,11.375700,9.665630,8.470140,15.190700,2.134140,1.665490,5.196470,8.92214,4.98055,11.346400,7.001000,2.62676,20.165800,4.159740,1.872830,12.90280,8.964900,15.359000,91.847100,8.48751,4.904450,4.557930,2.828820,9.31402,5.084460,4.091910,4.864660,7.10343,40.203200,9.28335,12.30500,14.246400,7.309020,2.010710,1.98562,2.535050,7.205750,18.865500,3.730100,1.748060,2.913690,3.524980,23.85200,1.868650,13.48300,5.349900,13.780300,3.602990,3.486760,33.692500,0.395513,8.237160,30.525400,10.718300,13.91340,4.396780,5.973760,3.350700,0.895223,9.665870,2.925060,19.899900,14.43840,10.576800,5.08876,11.460700,10.091900,9.326250,14.84080,5.95915,6.222740,2.415110,6.59075,11.82680,14.07070,10.159200,2.53030,2.912380,3.697280,0.359733,2.77869,13.866700,12.569800,3.488230,2.253910,1.08286,1.582650,4.251720,22.75370
4,A1BG-AS1,1.827090,1.059760,2.117120,1.245820,3.242580,0.669402,5.597850,1.339760,0.552307,0.649324,1.57104,1.20736,2.776230,1.210420,1.17964,4.118550,3.602640,0.221111,3.18057,3.334600,3.148970,4.134170,2.96816,2.184440,3.815960,3.178710,3.14951,1.629090,2.817680,2.408640,3.24197,5.939370,3.79430,5.12258,3.665250,3.185530,1.629620,0.64700,0.939661,0.930587,2.181560,1.331100,0.662754,0.868483,1.014070,6.13937,4.637700,1.79243,0.923945,2.077570,1.899980,2.453350,4.034170,0.711186,2.361100,7.065610,2.109460,2.51323,0.715256,0.750577,1.982590,1.507060,1.126790,0.814948,5.991130,1.80101,1.288600,2.44683,3.747710,5.110980,1.380890,2.63784,2.12112,2.573690,0.674932,1.54712,1.13957,2.21067,1.209590,1.22214,1.622530,1.008290,1.673490,1.83108,1.979040,1.958780,0.442682,0.785791,0.69881,0.900695,0.608497,4.34096

In [11]:
clinical.head()

  Sample ID Omniseq_RS_ID (RNAseq)
0   BACI170            RS-03238953
1   BACI191            RS-03238954
2   BACI192            RS-03238955
3   BACI190            RS-03238956
4   BACI160            RS-03238957

In [12]:
from pathlib import Path

for f in Path("../data/raw").iterdir():
    print(f.name)

.gitkeep
GSE176307_BACI_Omniseq_Sample_Name_Key_submitted_GEO_v2.csv.gz
GSE176307_salmon_tpm_gene.matrix.tsv.gz

In [4]:
Seq1 = "TGATACTAGATAG"
Seq2 = "GACTATCHATACG"

print("Number of G in Seq1:", Seq1.count("G"))
print("Number of G in Seq2:", Seq2.count("G"))

result = Seq1 + Seq1

print("Seq1 + Seq1:", result)

Number of G in Seq1: 3
Number of G in Seq2: 2
Seq1 + Seq1: TGATACTAGATAGTGATACTAGATAG